[build]
  base = "/build/repo"
  command = "npm run build"
  commandOrigin = "config"
  publish = "/build/repo/build"
  publishOrigin = "config"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200